version: '3.1'
services:
  db:
    restart: always
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    # privileged: true
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=WK5JbniQN
      - MYSQL_DATABASE=mydb
    volumes:
      - './data/db/mysql:/var/lib/mysql'
